# Generated by Django 5.1.6 on 2025-03-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmp', models.CharField(max_length=200, verbose_name='Empresa')),
                ('giro', models.CharField(max_length=200, verbose_name='Giro')),
                ('direccionEmp', models.CharField(max_length=250, verbose_name='Dirección de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UniEconomicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_uniEc', models.CharField(max_length=250, verbose_name='Unidad económica')),
                ('clase_uniEc', models.CharField(max_length=250, verbose_name='Clase de la unidad económica')),
                ('codigoPos', models.CharField(max_length=5, verbose_name='Codigo postal')),
                ('direc_uniEc', models.CharField(max_length=250, verbose_name='Dirección')),
                ('tel_uniEc', models.CharField(max_length=20, null=True, verbose_name='Telefono')),
                ('correp_uniEc', models.CharField(max_length=100, null=True, verbose_name='Correo')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitud')),
                ('long', models.CharField(max_length=50, verbose_name='Longitud')),
                ('status', models.CharField(choices=[('1', 'Cliente'), ('2', 'Prospecto'), ('3', 'No prospecto'), ('4', 'Cuenta ganada'), ('5', 'Descartado')], default=0, max_length=2, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSuc', models.CharField(max_length=200, verbose_name='Sucursal')),
                ('direccionSuc', models.CharField(max_length=250, verbose_name='Dirección de la sucursal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.empresa', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSuper', models.CharField(max_length=250, verbose_name='Supervisor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.sucursal', verbose_name='Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAses', models.CharField(max_length=250, verbose_name='Asesor')),
                ('rutaAses', models.CharField(max_length=250, verbose_name='Ruta')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.supervisor', verbose_name='Supervisor')),
            ],
        ),
    ]
