# Generated by Django 4.0.6 on 2025-03-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_unieconomicas_iduni'),
    ]

    operations = [
        migrations.AddField(
            model_name='unieconomicas',
            name='id_Uni',
            field=models.CharField(max_length=200, null=True, verbose_name='ID Unidades economicas'),
        ),
    ]
