# Generated by Django 4.0.6 on 2025-03-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_unieconomicas_id_uni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unieconomicas',
            name='Fecha_de_incorporacion_al_denue',
            field=models.CharField(max_length=20, null=True, verbose_name='Fecha de incorporación al denue'),
        ),
    ]
