# Generated by Django 4.0.6 on 2025-03-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_unieconomicas_fecha_de_incorporacion_al_denue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unieconomicas',
            name='Letra_exterior',
            field=models.CharField(max_length=200, null=True, verbose_name='Letra exterior'),
        ),
    ]
