# Generated by Django 4.0.6 on 2025-03-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_unieconomicas_numero_exterior_o_kilometro'),
    ]

    operations = [
        migrations.AddField(
            model_name='unieconomicas',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.asesor', verbose_name='Asesor'),
        ),
    ]
