# Generated by Django 4.0.6 on 2025-03-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_unieconomicas_asesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='unieconomicas',
            name='asesor',
        ),
        migrations.AddField(
            model_name='consulta',
            name='supervisor',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='leads.supervisor', verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='unieconomicas',
            name='cliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='unieconomicas',
            name='descarte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descartado'),
        ),
        migrations.AddField(
            model_name='unieconomicas',
            name='no_prosp',
            field=models.IntegerField(blank=True, null=True, verbose_name='No prospecto'),
        ),
        migrations.AddField(
            model_name='unieconomicas',
            name='prospecto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prospecto'),
        ),
    ]
