# Generated by Django 4.0.6 on 2025-03-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_delete_estado_remove_consulta_asesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unieconomicas',
            name='cliente',
            field=models.IntegerField(null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='unieconomicas',
            name='descarte',
            field=models.IntegerField(null=True, verbose_name='Descartado'),
        ),
        migrations.AlterField(
            model_name='unieconomicas',
            name='no_prosp',
            field=models.IntegerField(null=True, verbose_name='No prospecto'),
        ),
        migrations.AlterField(
            model_name='unieconomicas',
            name='prospecto',
            field=models.IntegerField(null=True, verbose_name='Prospecto'),
        ),
    ]
