# Generated by Django 4.0.6 on 2025-03-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_unieconomicas_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unieconomicas',
            name='Entidad_federetiva',
            field=models.CharField(max_length=250, null=True, verbose_name='Estadoo'),
        ),
    ]
