# Generated by Django 4.0.6 on 2025-03-21 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_unieconomicas_entidad_federetiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.supervisor', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='unieconomicas',
            name='Entidad_federetiva',
            field=models.CharField(max_length=250, null=True, verbose_name='Estado'),
        ),
    ]
