# Generated by Django 4.0.6 on 2025-03-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
